import streamlit as st
import sys
from pathlib import Path
import config

# Add parent directory to path
sys.path.append(str(Path(__file__).parent.parent))

from utils.auth import require_auth, init_session_state
from models.login import LoginModel
from models.text_origin_classifier import TextOriginClassifier
from database.db_manager import DatabaseManager
import plotly.graph_objects as go
import pandas as pd

# Page config
st.set_page_config(
    page_title="AI/Human Detection",
    page_icon="🤖",
    layout="wide"
)

# Custom CSS for Origin Classifier
st.markdown("""
<style>
    .result-badge {
        display: inline-block;
        padding: 0.75rem 2rem;
        border-radius: 30px;
        font-weight: bold;
        font-size: 1.4rem;
        margin: 1rem 0;
        box-shadow: 0 6px 15px rgba(0,0,0,0.1);
    }
    
    /* Styles specific to AI/Human classes */
    .HumanWritten0 { background: #2ecc71; color: white; } /* Human */
    .AIGenerated1 { background: #e74c3c; color: white; } /* Machine/AI */
    
    .confidence-high { color: #2ecc71; font-weight: bold; }
    .confidence-medium { color: #f39c12; font-weight: bold; }
    .confidence-low { color: #e74c3c; font-weight: bold; }
</style>
""", unsafe_allow_html=True)

# Initialize
init_session_state()

def main():
        
    if st.session_state.logged_in: 

        st.title("🤖 AI/Human Origin Detection")
        st.markdown("Analyze text to determine if it was written by a human (0) or generated by a machine (1).")
        
        # Initialize models
        if 'origin_classifier' not in st.session_state:
            with st.spinner("Loading Text Origin model..."):
                try:
                    st.session_state.origin_classifier = TextOriginClassifier()
                except FileNotFoundError as e:
                    st.error(f"Model Error: {e}")
                    st.stop()
        
        classifier = st.session_state.origin_classifier
        db = DatabaseManager() 
        
        # --- Classification Tab ---
        st.markdown("### Enter Text for Analysis")
        
        col1, col2 = st.columns([2, 1])
        
        with col1:
            # Input
            text_input = st.text_area(
                "Text to Analyze",
                height=300,
                placeholder="Paste your essay, article, or long text here...",
                help="Longer texts (e.g., essays) typically yield more reliable results."
            )
            
        with col2:
            st.markdown("### 🎯 Classification Classes")
            st.success("**Human Written (0)**: Text exhibits characteristics often found in human-written content (e.g., variety, specific tone).")
            st.error("**AI Generated (1)**: Text exhibits predictable structure and vocabulary common in large language model outputs.")
        
        # Classify button
        if st.button("🔍 Determine Origin", type="primary", use_container_width=True):
            if text_input and len(text_input.strip()) > 50:
                with st.spinner("Analyzing text origin..."):
                    try:
                        # Predict
                        prediction, confidence, scores = classifier.predict(text_input)
                        
                        # Save to database (using a dedicated model identifier)
                        db.save_origin(
                            st.session_state.user_id,
                            text_input,
                            prediction,
                            confidence
                        )
                        
                        # --- Display Results ---
                        st.markdown("---")
                        st.markdown("## 🎯 Origin Detection Results")
                        
                        col1, col2, col3 = st.columns([2, 1, 1])
                        
                        with col1:
                            # Category badge
                            category_class = prediction.replace(" ", "").replace("(", "").replace(")", "")
                            st.markdown(f"""
                                <div style="text-align: center;">
                                    <h3>Predicted Origin</h3>
                                    <span class="result-badge {category_class}">{prediction}</span>
                                </div>
                            """, unsafe_allow_html=True)
                        
                        conf_class = "confidence-high" if confidence > 0.7 else "confidence-medium" if confidence > 0.5 else "confidence-low"
                        
                        with col2:
                            # Confidence
                            st.markdown(f"""
                                <div style="text-align: center;">
                                    <h3>Confidence</h3>
                                    <p class="{conf_class}" style="font-size: 2rem;">{confidence*100:.1f}%</p>
                                </div>
                            """, unsafe_allow_html=True)
                        
                        with col3:
                            # Status
                            if confidence > 0.7:
                                st.success("✅ High Confidence")
                            elif confidence > 0.5:
                                st.warning("⚠️ Medium Confidence")
                            else:
                                st.error("❌ Low Confidence")
                        
                        # Probability distribution
                        st.markdown("### 📊 Probability Distribution")
                        
                        df_scores = pd.DataFrame(
                            {'Origin': list(scores.keys()), 'Probability (%)': [v * 100 for v in scores.values()]}
                        ).sort_values(by='Probability (%)', ascending=False)
                        
                        fig = go.Figure(data=[
                            go.Bar(
                                x=df_scores['Origin'],
                                y=df_scores['Probability (%)'],
                                marker_color=['#2ecc71', '#e74c3c'],
                                text=[f"{v:.1f}%" for v in df_scores['Probability (%)']],
                                textposition='auto',
                            )
                        ])
                        
                        fig.update_layout(
                            xaxis_title="Origin Class",
                            yaxis_title="Probability (%)",
                            yaxis_range=[0, 100],
                            height=400,
                            showlegend=False
                        )
                        
                        st.plotly_chart(fig, use_container_width=True)
                        
                        # Analysis
                        st.markdown("### 💡 Analysis")
                        if confidence > 0.8:
                            st.info(f"The text is almost certainly **{prediction}**. The features analyzed strongly support this classification.")
                        elif confidence > 0.6:
                            st.warning(f"The text is likely **{prediction}**, but the confidence is moderate, suggesting some ambiguity in style or structure.")
                        else:
                            st.error(f"The classification suggests **{prediction}**, but confidence is low. The text may be too short, or the writing style is highly mixed.")
                            
                    except Exception as e:
                        st.error(f"An error occurred during prediction: {e}")
            else:
                st.error("Please enter a text with at least 50 characters for accurate analysis.")

    else:
        
        LoginModel.login()

if __name__ == "__main__":
    main()