import streamlit as st
import sys
from pathlib import Path

# Add parent directory to path
sys.path.append(str(Path(__file__).parent.parent))

from utils.auth import require_auth, init_session_state
from models.yahoo_news_classifier import YahooAnswersClassifier, YAHOO_CATEGORIES
from database.db_manager import DatabaseManager
import plotly.graph_objects as go
import pandas as pd

# Page config
st.set_page_config(
    page_title="Yahoo Topic Classification",
    page_icon="❓",
    layout="wide"
)

# Custom CSS for Yahoo Classifier
st.markdown("""
<style>
    .result-badge {
        display: inline-block;
        padding: 0.75rem 2rem;
        border-radius: 30px;
        font-weight: bold;
        font-size: 1.4rem;
        margin: 1rem 0;
        box-shadow: 0 6px 15px rgba(0,0,0,0.1);
        background: #3498db; 
        color: white;
    }
    
    .confidence-high { color: #2ecc71; font-weight: bold; }
    .confidence-medium { color: #f39c12; font-weight: bold; }
    .confidence-low { color: #e74c3c; font-weight: bold; }
</style>
""", unsafe_allow_html=True)

# Global color palette for charts 
YAHOO_COLORS = [
    '#e60049', '#0bb4ff', '#50e991', '#e6d800', '#9b19f5', '#ffa300', 
    '#dc0ab4', '#b3d4ff', '#00bfa0', '#3477e0'
]

# Initialize
init_session_state()

@require_auth
def main():
    st.title("❓ Yahoo! Answers Topic Classification")
    st.markdown("Categorize questions, content, and answers into 10 major topics from the Yahoo! Answers dataset.")
    
    # Initialize models
    if 'yahoo_classifier' not in st.session_state:
        with st.spinner("Loading Yahoo Answers model..."):
            try:
                st.session_state.yahoo_classifier = YahooAnswersClassifier()
            except FileNotFoundError as e:
                st.error(f"Model Error: {e}. Please ensure the model files were generated by the training script.")
                st.stop()
    
    classifier = st.session_state.yahoo_classifier
    db = DatabaseManager() 
    
    # --- Classification Tab ---
    st.markdown("### Enter Question Content")
    
    col1, col2 = st.columns([2, 1])
    
    with col1:
        # Input
        text_input = st.text_area(
            "Question Title, Content, and Best Answer (Combined)",
            height=300,
            placeholder="Example: Why is the sky blue? Is it because of the water in the atmosphere? The sky is blue because of Rayleigh scattering...",
            help="The model was trained on a concatenation of the title, question, and best answer. Combining these yields the best results."
        )
        
    with col2:
        st.markdown("### 📚 10 Topics")
        st.markdown(", ".join(f"**{cat}**" for cat in YAHOO_CATEGORIES))
        if not classifier.supports_proba:
            st.warning("⚠️ **Model Limitation:** This model (LinearSVC) does not reliably provide prediction confidence scores.")
    
    # Classify button
    if st.button("🔍 Classify Topic", type="primary", use_container_width=True):
        if text_input and len(text_input.strip()) > 50:
            with st.spinner("Analyzing Yahoo topic..."):
                try:
                    # Predict
                    prediction, confidence, scores = classifier.predict(text_input)
                    
                    # Save to database
                    db.save_classification(
                        st.session_state.user_id,
                        text_input,
                        f"Yahoo: {prediction}",
                        confidence
                    )
                    
                    # --- Display Results ---
                    st.markdown("---")
                    st.markdown("## 🎯 Topic Classification Results")
                    
                    col1, col2, col3 = st.columns([2, 1, 1])
                    
                    with col1:
                        # Category badge
                        st.markdown(f"""
                            <div style="text-align: center;">
                                <h3>Predicted Topic</h3>
                                <span class="result-badge">{prediction}</span>
                            </div>
                        """, unsafe_allow_html=True)
                    
                    conf_class = "confidence-high" if confidence > 0.7 else "confidence-low" if confidence == 0.0 and not classifier.supports_proba else "confidence-medium"
                    
                    with col2:
                        # Confidence
                        if classifier.supports_proba:
                            st.markdown(f"""
                                <div style="text-align: center;">
                                    <h3>Confidence</h3>
                                    <p class="{conf_class}" style="font-size: 2rem;">{confidence*100:.1f}%</p>
                                </div>
                            """, unsafe_allow_html=True)
                        else:
                            st.markdown(f"""
                                <div style="text-align: center;">
                                    <h3>Confidence</h3>
                                    <p class="confidence-low" style="font-size: 1.5rem;">N/A</p>
                                </div>
                            """, unsafe_allow_html=True)
                    
                    with col3:
                        # Status
                        if not classifier.supports_proba:
                             st.info("ℹ️ Only category is available.")
                        elif confidence > 0.7:
                            st.success("✅ High Confidence")
                        elif confidence > 0.5:
                            st.warning("⚠️ Medium Confidence")
                        else:
                            st.error("❌ Low Confidence")
                    
                    # Probability distribution
                    st.markdown("### 📊 Score Distribution")
                    
                    df_scores = pd.DataFrame(
                        {'Topic': list(scores.keys()), 'Score (%)': [v * 100 for v in scores.values()]}
                    ).sort_values(by='Score (%)', ascending=False)
                    
                    fig = go.Figure(data=[
                        go.Bar(
                            x=df_scores['Topic'],
                            y=df_scores['Score (%)'],
                            marker_color=YAHOO_COLORS[:len(df_scores)],
                            text=[f"{v:.1f}%" for v in df_scores['Score (%)']],
                            textposition='auto',
                        )
                    ])
                    
                    fig.update_layout(
                        xaxis_title="Topic",
                        yaxis_title="Score (Pseudo-Prob)",
                        yaxis_range=[0, 100],
                        height=450,
                        showlegend=False
                    )
                    
                    st.plotly_chart(fig, use_container_width=True)
                    
                    # Analysis
                    st.markdown("### 💡 Analysis")
                    st.info(f"The text was classified into the **{prediction}** topic. This classification relies purely on the LinearSVC model's primary output.")
                        
                except Exception as e:
                    st.error(f"An error occurred during prediction: {e}")
        else:
            st.error("Please enter sufficient text (e.g., a question and an answer) for accurate classification.")

if __name__ == "__main__":
    main()